#spring.application.name=auth-service
#server.port = 4003
#
##spring.datasource.url=jdbc:postgres://auth-service-db:5432/db
##spring.datasource.username=postgresql
##spring.datasource.password=pass123
##spring.jpa.hibernate.ddl-auto= update
#spring.jpa.show-sql=true

spring:
  application:
    name: auth-service
  jpa:
    show-sql: true

server:
  port: 4003

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

