server:
  port: 4040

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        - id: billing-service-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=1
        - id: analytics-service-route
          uri: http://billing-service:4002
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=1

        - id: auth-service-route
          uri: http://auth-service:4003
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
